# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{calais}
  s.version = "0.0.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Abhay Kumar"]
  s.date = %q{2010-08-02}
  s.description = %q{A Ruby interface to the Calais Web Service}
  s.email = %q{info@opensynapse.net}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "CHANGELOG.markdown",
     "Gemfile",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "lib/calais.rb",
     "lib/calais/client.rb",
     "lib/calais/error.rb",
     "lib/calais/response.rb"
  ]
  s.homepage = %q{http://github.com/abhay/calais}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{calais}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby interface to the Calais Web Service}
  s.test_files = [
    "spec/calais/client_spec.rb",
     "spec/calais/response_spec.rb",
     "spec/helper.rb"
  ]

  s.add_dependency("nokogiri", ">= 1.3.3")
  s.add_dependency("json", ">= 1.1.3")

  s.add_development_dependency("rspec", ">= 2.0.0")
end

